* Todos [72%]
- [X] remove the old x-main functions
- [X] remove unused / commented out code
- [X] handle footnotes formats for all html that goes into create-meta...
- [X] make the base template functions available to all
- [ ] only load the base template if it exists
- [X] add utility fnctions to template.clj, or remove it and add to core if it stays that empty
- [X] fix projects/sites, so that they can easily be merged into the index. maybe they have to return the meta
- [ ] check if there's an easy to solution to merging javascript / css / compiling it
- [X] merge the default.clj (etc) into a define-template call again
- [X] move all new options back to config.clj
- [ ] where possible make map to pmap again
- [ ] where possilbe, add some memoization
- [X] move html templates to public with _ for easier html working.
- [X] actually use the footnotes structures, right now they're part of either the markdown or the org html export. kinda difficult to get them out.
- [X] toc:nil always has to be included, use another option for unpublished site stuff!
- [X] change the archive, so that all stuff will be shown in one long list (with date entries) for better SEO performance
- [ ] the distinctions between keywords/tags tags/categories projects/site site/page are confusing, it would be really nice to refactor most of that
- [X] keywords for orgmarkdown posts should also make it into the site keyword lists, not just tags, need to refactor enhance-metadata to also include (:keywords m)
- [ ] now that the api is stable again, take care of the tests
- [ ] create an introductory description
  
